### ISSUE TITLE
Cannot write the root file

### ISSUE THREAD

**Issue by pellegri** [adrien-matta/nptool#61]
Good day,

I encounter a problem when running the benchmark and the examples. In both case the root file couldn't be written.
I followed the installation instructions and the simulations are running fine. Only when attempting to run events and write to root file I cannot do so.
Below the error:

Error in <TFile::WriteTObject>: Directory /home/lpellegri/Software/nptool/Outputs/Simulation//Example1.root is not writable
  -> Number of bites written to file: 0
Error in <TFile::cd>: No such file /home/lpellegri/Software/nptool/Outputs/Simulation//Example1.root:/

The Output folder has full rights so cannot be that is not writable.
I can see that there are two // in the path but not sure why.

Have you had this problem before? Can you help me with this?

Thank you.
Regards,
Luna

**Comment by adrien-matta** [comment]
Dear Luna,

Thanks for your message and for using nptool.

We moved to a new repository at gitlab.in2p3.fr/np/nptool a few years ago. Did you use the version from gitlab or from github? If you followed the install process from website then you installed the version from gitlab.
You can login to gitlab.in2p3.fr with Edugain which will redirect you to your SAFIRE login portal.

Looking at your bug I added a couple of line in the RootOuptput class to prevent the issue with double // to appears in path. Most system do not care about them but some are more picky.

To pull the new version, try the following command:
npl
git pull
make install

Let me know this should solve the issue. 

Best regards,
Adrien.

**Comment by pellegri** [comment]
Dear Adrien,

Thank you for your prompt response.
I will give it a try with the updated version and will come back to you if any problems.

Thank you so much for the help.

Regards,
Luna

**Comment by pellegri** [comment]
I have pulled and recompile the code but I still have that problem.
Now the double // is gone but it doesn't take the name of the root file anymore. See below:

Error in <TFile::WriteTObject>: Directory /home/lpellegri/Software/nptool/Outputs/Simulation/.root is not writable
  -> Number of bites written to file: 0
Error in <TFile::cd>: No such file /home/lpellegri/Software/nptool/Outputs/Simulation/.root:/

**Comment by adrien-matta** [comment]
Dear Luna,

Sorry, I just saw that I did not code the else part of the if statement. I just made a new commit that should fix the issue.
Let me know if this solve the issue.

Best Regards,
Adrien.

**Comment by pellegri** [comment]
Now the path is fine but still not working. The folder has all the writable permission though.

drwxrwxrwx  2 lpellegri lpellegri 4096 Jun 26 13:12 Outputs

Error in <TFile::WriteTObject>: Directory /home/lpellegri/Software/nptool/Outputs/Simulation/Example1.root is not writable
  -> Number of bites written to file: 0
Error in <TFile::cd>: No such file /home/lpellegri/Software/nptool/Outputs/Simulation/Example1.root:/

**Comment by adrien-matta** [comment]
Dear Luna,

I just ran some test and I found what the issue is. file that kept the Simulation and Analysis folder in the repo were removed a few weeks ago by mistake, that is what is causing the error, as /home/lpellegri/Software/nptool/Outputs/Simulation folder does not exist. I will fix this but you can simply do this:
cd /home/lpellegri/Software/nptool/Outputs/
mkdir Simulation Analysis

and then it should work. Sorry for this bug, I will fix this.

Let me know if this fix the issue.

Best regards,
Adrien.

**Comment by pellegri** [comment]
Awesome!! After creating the folders it works.
Thank you so much for the help.

Regards,
Luna
